# Generated by Django 6.0 on 2025-12-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('retourne', 'Retourné'), ('en_retard', 'En retard')], default='en_cours', max_length=20),
        ),
    ]
